jupyterhub:
  hub:
    db:
      password: <path:projects/362159383816/secrets/jupyterhub-admin-password#jupyterhub-admin-password>
    config:
      JupyterHub:
        admin_access: false
  proxy:
    secretToken: <path:projects/362159383816/secrets/jupyterhub-admin-password#jupyterhub-admin-password>