jupyterhub:
  hub:
    db:
      password: <path:projects/362159383816/secrets/jupyterhub-admin-password#jupyterhub-admin-password>
    config:
      Authenticator:
        admin_users:
          - admin1
        allowed_users:
          - user1
    # ...
      DummyAuthenticator:
        password: <path:projects/362159383816/secrets/jupyterhub-admin-password#jupyterhub-admin-password>
    #   JupyterHub:
    #     admin_access: false
  proxy:
    # service:
    #   type: ClusterIP
    secretToken: <path:projects/362159383816/secrets/jupyterhub-admin-password#jupyterhub-admin-password>