apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
spec:
  project: database
  source:
    path: 'postgresql'
    repoURL: 'https://github.com/dounpct/argocd-deployment.git'
    targetRevision: master
    plugin:
      env:
        - name:  INIT_ARGS
          value: "helm dep update"
        - name:  ARG_PARAMETERS
          value: "helm template postgresql -n postgresql . -f values/values.yaml "
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
  syncPolicy:
    syncOptions:
      - CreateNamespace=true