apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  project: ingress-nginx
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.6.0
    chart: ingress-nginx
    helm:
      values: |
        controller:
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 300m
              memory: 200Mi
          autoscaling:
            apiVersion: autoscaling/v2
            enabled: true
            annotations: {}
            minReplicas: 1
            maxReplicas: 11
            targetCPUUtilizationPercentage: 70
            targetMemoryUtilizationPercentage: 70
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true