apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-operator
spec:
  project: default
  source:
    path: 'awx-operator'
    repoURL: 'https://github.com/dounpct/argocd-deployment.git'
    targetRevision: master
    plugin:
      env:
        - name:  INIT_ARGS
          value: "helm dep update"
        - name:  ARG_PARAMETERS
          value: "helm template awx-operator -n awx-operator . -f values/values.yaml "
  destination:
    server: https://kubernetes.default.svc
    namespace: awx-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true