apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  project: ingress-nginx
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.6.0
    chart: ingress-nginx
    helm:
      values: |
        limits:
          cpu: 200m
          memory: 190Mi
        requests:
          cpu: 100m
          memory: 90Mi
        autoscaling:
          apiVersion: autoscaling/v2
          enabled: false
          annotations: {}
          minReplicas: 1
          maxReplicas: 11
          targetCPUUtilizationPercentage: 50
          targetMemoryUtilizationPercentage: 50
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true