apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-operator
spec:
  project: default
  source:
    repoURL: 'https://ansible.github.io/awx-operator'
    targetRevision: 2.5.1
    chart: awx-operator
    # helm:
    #   values: |
    #     controller:
    #       resources:
    #         limits:
    #           cpu: 500m
    #           memory: 500Mi
    #         requests:
    #           cpu: 300m
    #           memory: 200Mi
    #       autoscaling:
    #         apiVersion: autoscaling/v2
    #         enabled: true
    #         annotations: {}
    #         minReplicas: 1
    #         maxReplicas: 11
    #         targetCPUUtilizationPercentage: 70
    #         targetMemoryUtilizationPercentage: 70
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: awx-operator
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true