apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: cmp-plugin
    spec:
      version: v1.0
      init:
        command: ["/bin/sh", "-c"]
        args: ["$ARGOCD_ENV_INIT_ARGS"]
      generate:
        command: [sh, -c]
        args: ["$ARGOCD_ENV_ARG_PARAMETERS | argocd-vault-plugin generate - "]
      discover:
        find:
          command: [sh, -c, find . -name *.yaml]