apiVersion: v1
kind: Secret
metadata:
  name: gcr-authen
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <path:projects/362159383816/secrets/GCR_DOCKERCONFIGJSON#GCR_DOCKERCONFIGJSON | base64encode>
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: jenkins-secret-data
stringData:
  {{- toYaml .Values.secret | nindent 2 }}
