apiVersion: v1	
data:	
  jcasc-default-config.yaml: |-	
    jenkins:	
      authorizationStrategy:	
        loggedInUsersCanDoAnything:	
          allowAnonymousRead: false	
      securityRealm:	
        local:	
          allowsSignup: false	
          enableCaptcha: false	
          users:	
          - id: "${chart-admin-username}"	
            name: "Jenkins Admin"	
            password: "${chart-admin-password}"	
      disableRememberMe: false	
      mode: NORMAL	
      numExecutors: 2	
      labelString: ""	
      projectNamingStrategy: "standard"	
      markupFormatter:	
        plainText	
      clouds:	
      - kubernetes:	
          containerCapStr: "10"	
          defaultsProviderTemplate: ""	
          connectTimeout: "5"	
          readTimeout: "15"	
          jenkinsUrl: "http://jenkins.cicd.svc.cluster.local:8080"	
          jenkinsTunnel: "jenkins-agent.cicd.svc.cluster.local:50000"	
          maxRequestsPerHostStr: "32"	
          name: "kubernetes"	
          namespace: "cicd"	
          serverUrl: "https://kubernetes.default"	
          podLabels:	
          - key: "jenkins/jenkins-jenkins-agent"	
            value: "true"	
          templates:	
            - name: "default"	
              namespace: "cicd"	
              id: 682b16ba5da08f7e7943c84672950ecb58545a090d259587b3f90fe97220a7ba	
              containers:	
              - name: "jnlp"	
                alwaysPullImage: false	
                args: "^${computer.jnlpmac} ^${computer.name}"	
                command: 	
                envVars:	
                  - envVar:	
                      key: "JENKINS_URL"	
                      value: "http://jenkins.cicd.svc.cluster.local:8080/"	
                image: "jenkins/inbound-agent:4.11.2-4"	
                privileged: "false"	
                resourceLimitCpu: 512m	
                resourceLimitMemory: 512Mi	
                resourceRequestCpu: 512m	
                resourceRequestMemory: 512Mi	
                runAsUser: 	
                runAsGroup: 	
                ttyEnabled: false	
                workingDir: /home/jenkins/agent	
              idleMinutes: 0	
              instanceCap: 2147483647	
              label: "jenkins-jenkins-agent "	
              nodeUsageMode: "NORMAL"	
              podRetention: Never	
              showRawYaml: true	
              serviceAccount: "default"	
              slaveConnectTimeoutStr: "100"	
              yamlMergeStrategy: override	
      crumbIssuer:	
        standard:	
          excludeClientIPFromCrumb: true	
    security:	
      apiToken:	
        creationOfLegacyTokenEnabled: false	
        tokenGenerationOnCreationEnabled: false	
        usageStatisticsEnabled: true	
    unclassified:	
      location:	
        adminAddress: 	
        url: http://jenkins:8080	
kind: ConfigMap	
metadata:	
  annotations:	
    kubectl.kubernetes.io/last-applied-configuration: >	
      {"apiVersion":"v1","data":{"jcasc-default-config.yaml":"jenkins:\n 	
      authorizationStrategy:\n    loggedInUsersCanDoAnything:\n     	
      allowAnonymousRead: false\n  securityRealm:\n    local:\n     	
      allowsSignup: false\n      enableCaptcha: false\n      users:\n      - id:	
      \"${chart-admin-username}\"\n        name: \"Jenkins Admin\"\n       	
      password: \"${chart-admin-password}\"\n  disableRememberMe: false\n  mode:	
      NORMAL\n  numExecutors: 2\n  labelString: \"\"\n  projectNamingStrategy:	
      \"standard\"\n  markupFormatter:\n    plainText\n  clouds:\n  -	
      kubernetes:\n      containerCapStr: \"10\"\n     	
      defaultsProviderTemplate: \"\"\n      connectTimeout: \"5\"\n     	
      readTimeout: \"15\"\n      jenkinsUrl:	
      \"http://jenkins.cicd.svc.cluster.local:8080\"\n      jenkinsTunnel:	
      \"jenkins-agent.cicd.svc.cluster.local:50000\"\n     	
      maxRequestsPerHostStr: \"32\"\n      name: \"kubernetes\"\n     	
      namespace: \"cicd\"\n      serverUrl:	
      \"https://kubernetes.default\"\n      podLabels:\n      - key:	
      \"jenkins/jenkins-jenkins-agent\"\n        value: \"true\"\n     	
      templates:\n        - name: \"default\"\n          namespace:	
      \"cicd\"\n          id:	
      682b16ba5da08f7e7943c84672950ecb58545a090d259587b3f90fe97220a7ba\n         	
      containers:\n          - name: \"jnlp\"\n            alwaysPullImage:	
      false\n            args: \"^${computer.jnlpmac}	
      ^${computer.name}\"\n            command: \n           	
      envVars:\n              - envVar:\n                  key:	
      \"JENKINS_URL\"\n                  value:	
      \"http://jenkins.cicd.svc.cluster.local:8080/\"\n            image:	
      \"jenkins/inbound-agent:4.11.2-4\"\n            privileged:	
      \"false\"\n            resourceLimitCpu: 512m\n           	
      resourceLimitMemory: 512Mi\n            resourceRequestCpu:	
      512m\n            resourceRequestMemory: 512Mi\n            runAsUser:	
      \n            runAsGroup: \n            ttyEnabled: false\n           	
      workingDir: /home/jenkins/agent\n          idleMinutes: 0\n         	
      instanceCap: 2147483647\n          label: \"jenkins-jenkins-agent	
      \"\n          nodeUsageMode: \"NORMAL\"\n          podRetention:	
      Never\n          showRawYaml: true\n          serviceAccount:	
      \"default\"\n          slaveConnectTimeoutStr: \"100\"\n         	
      yamlMergeStrategy: override\n  crumbIssuer:\n    standard:\n     	
      excludeClientIPFromCrumb: true\nsecurity:\n  apiToken:\n   	
      creationOfLegacyTokenEnabled: false\n    tokenGenerationOnCreationEnabled:	
      false\n    usageStatisticsEnabled: true\nunclassified:\n  location:\n   	
      adminAddress: \n    url:	
      http://jenkins:8080"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"jenkins-controller","app.kubernetes.io/instance":"jenkins","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"jenkins","argocd.argoproj.io/instance":"jenkins","helm.sh/chart":"jenkins-4.3.0","jenkins-jenkins-config":"true"},"name":"jenkins-jenkins-jcasc-config","namespace":"cicd"}}	
  labels:	
    app.kubernetes.io/component: jenkins-controller	
    app.kubernetes.io/instance: jenkins	
    app.kubernetes.io/managed-by: Helm	
    app.kubernetes.io/name: jenkins	
    argocd.argoproj.io/instance: jenkins	
    helm.sh/chart: jenkins-4.3.0	
    jenkins-jenkins-config: 'true'	
  managedFields:	
    - apiVersion: v1	
      fieldsType: FieldsV1	
      fieldsV1:	
        'f:data':	
          .: {}	
          'f:jcasc-default-config.yaml': {}	
        'f:metadata':	
          'f:annotations':	
            .: {}	
            'f:kubectl.kubernetes.io/last-applied-configuration': {}	
          'f:labels':	
            .: {}	
            'f:app.kubernetes.io/component': {}	
            'f:app.kubernetes.io/instance': {}	
            'f:app.kubernetes.io/managed-by': {}	
            'f:app.kubernetes.io/name': {}	
            'f:argocd.argoproj.io/instance': {}	
            'f:helm.sh/chart': {}	
            'f:jenkins-jenkins-config': {}	
      manager: argocd-controller	
      operation: Update	
      time: '2023-01-26T07:16:19Z'	
  name: jenkins-jenkins-jcasc-config	
  namespace: cicd	
  resourceVersion: '23664349'	
  uid: 0f4ba211-9457-4647-a511-99f731877138