jenkins:
  controller:
    image: "asia.gcr.io/gcp-dmp-devops/cicd/jenkins/jenkins-jcasc"
    tag: "2.319.2-master"
    imagePullSecretName: "gcr-authen"
    serviceType: LoadBalancer
    numExecutors: 2                            #default 0 and can not run script at master node

  persistence:
    size: "55Gi"