jenkins:
  controller:
    image: "asia.gcr.io/gcp-dmp-devops/cicd/jenkins/jenkins-jcasc"
    tag: "2.319.2-master"
    imagePullSecretName: "gcr-authen"
    installPlugins: false
    serviceType: LoadBalancer
    numExecutors: 2                            #default 0 and can not run script at master node

    configUrls:
      - https://storage.googleapis.com/devops-integration-config/jenkins-jcasc-config/develop/jenkins-jcasc-sandbox.yaml?ignoreCache=3
  persistence:
    size: "55Gi"