jenkins:
  controller:
    image: "asia.gcr.io/gcp-dmp-devops/cicd/jenkins/jenkins-jcasc"
    tag: "0.0.1-master"
    imagePullSecretName: "gcr-authen"
    installPlugins: false
    serviceType: LoadBalancer
    numExecutors: 2                            #default 0 and can not run script at master node
    existingSecret: "jenkins-secret-data"
    JCasC:
      configUrls: https://storage.googleapis.com/devops-integration-config/jenkins-jcasc-config/develop/jenkins-jcasc-test-jiw-2.yaml?ignoreCache=8
  persistence:
    size: "55Gi"
  
secret:
  JENKINS_NAME: "JIW"
  JENKINS_URL: "http://34.142.171.125:8080/"
  GCP_KEY_FILE_BYTES: <path:projects/362159383816/secrets/GCP_KEY_FILE_BYTES#GCP_KEY_FILE_BYTES>
  GITHUB_APP_READ: <path:projects/362159383816/secrets/GITHUB_APP_READ#GITHUB_APP_READ>

