jenkins:
  controller:
    image: "asia.gcr.io/gcp-dmp-devops/cicd/jenkins/jenkins-jcasc"
    tag: "0.0.1-master"
    imagePullSecretName: "gcr-authen"
    installPlugins: false
    serviceType: LoadBalancer
    numExecutors: 2                            #default 0 and can not run script at master node
    
    JCasC:
      configUrls:
        - https://storage.googleapis.com/devops-integration-config/jenkins-jcasc-config/develop/jenkins-jcasc-test-jiw-2.yaml?ignoreCache=6
  persistence:
    size: "55Gi"

