jenkins:
  controller:
    image: "asia.gcr.io/gcp-dmp-devops/cicd/jenkins/jenkins-jcasc"
    tag: "0.0.1-master"
    imagePullSecretName: "gcr-authen"
    installPlugins: false
    serviceType: LoadBalancer
    numExecutors: 2                            #default 0 and can not run script at master node
    customJenkinsLabels:
      - "master"
    existingSecret: "jenkins-secret-data"
    adminPassword: <path:projects/362159383816/secrets/jenkins_admin_password#jenkins_admin_password>
    jenkinsUrl: "http://34.142.171.125:8080/"
    jenkinsAdminEmail: sutee.kon@truedigital.com
    JCasC:
      configScripts:
        welcome-message: |
          jenkins:
            systemMessage: Welcome to our CI\CD server.
        jenkins-credentials: |
          credentials:
            system:
              domainCredentials:
              - credentials:
                - usernamePassword:
                    scope: GLOBAL
                    id: 'AWS_CREDENTIAL'
                    username: ${AWS_ACCESS_KEY_ID}
                    password: ${AWS_SECRET_ACCESS_KEY}

      configUrls: https://storage.googleapis.com/devops-integration-config/jenkins-jcasc-config/develop/jenkins-jcasc-test-jiw-2.yaml?ignoreCache=21      
  
  agent:
    additionalContainers:
    - sideContainerName: dind
      image: docker
      tag: dind
      command: dockerd-entrypoint.sh
      args: ""
      privileged: true
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1
          memory: 2Gi
    podTemplates:
      python: |
        - name: python
          label: jenkins-python
          serviceAccount: jenkins
          containers:
            - name: python
              image: python:3
              command: "/bin/sh -c"
              args: "cat"
              ttyEnabled: true
              privileged: true
              resourceRequestCpu: "400m"
              resourceRequestMemory: "512Mi"
              resourceLimitCpu: "1"
              resourceLimitMemory: "1024Mi"
  persistence:
    size: "70Gi"
  
secret:
  JENKINS_NAME: "JIW"
  JENKINS_URL: "http://34.142.171.125:8080/"
  JENKINS_ADMIN_PASSWORD: <path:projects/362159383816/secrets/jenkins_admin_password#jenkins_admin_password>
  GCP_KEY_FILE_BYTES: <path:projects/362159383816/secrets/GCP_KEY_FILE_BYTES#GCP_KEY_FILE_BYTES>
  GITHUB_APP_READ: <path:projects/362159383816/secrets/GITHUB_APP_READ#GITHUB_APP_READ>
  JENKINS_SLAVE_SECRET: <path:projects/362159383816/secrets/terraform-cluster-01-jenkins-slave-secret#terraform-cluster-01-jenkins-slave-secret>

