apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-serving
  labels:
    app: serve-ML-model-mlflow

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-serving
  template:
    metadata:
      labels:
        app: mlflow-serving

    spec:
      containers:
        - name: mlflow-serving
          image: asia.gcr.io/gcp-dmp-devops/cicd/devops/mlflow_serving:v1 #change here
          env:
            - name: MODEL_URI
              value: "gs://mlflow_gke_test_20230314/5/8911fc4e3a514e969cac16d157b008ed/artifacts/model" #change here
            - name: SERVING_PORT
              value: "8082"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/secrets/keyfile.json"
          volumeMounts:
            - name: gcsfs-creds
              mountPath: "/etc/secrets"
              readOnly: true
          resources:
            limits:
              cpu: 1000m
              memory: 600Mi
            requests:
              cpu: 500m
              memory: 300Mi
      imagePullSecrets:
      - name: gcr-authen
      
      volumes:
        - name: gcsfs-creds
          secret:
            secretName: gcsfs-creds
            items:
              - key: keyfile.json
                path: keyfile.json
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mlflow-serving
  name: mlflow-serving
spec:
  ports:
  - name: http-web
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: mlflow-serving
  type: ClusterIP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mlflow-serving
spec:
  minReplicas: 1  
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mlflow-serving
  targetCPUUtilizationPercentage: 60