apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gcsfs-creds
data:
  keyfile.json: <path:projects/362159383816/secrets/google_credentials_json#google_credentials_json | base64encode>
---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: gcr-authen
# type: kubernetes.io/dockerconfigjson
# data:
#   .dockerconfigjson: <path:projects/362159383816/secrets/GCR_DOCKERCONFIGJSON#GCR_DOCKERCONFIGJSON | base64encode>