apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gcsfs-creds
data:
  keyfile.json: <path:projects/362159383816/secrets/google_credentials_json#google_credentials_json | base64encode>
---
apiVersion: v1
kind: Secret
metadata:
  name: gcr-authen
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <path:projects/362159383816/secrets/GCR_DOCKERCONFIGJSON#GCR_DOCKERCONFIGJSON | base64encode>
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: basic-auth
data:
  auth: <path:projects/362159383816/secrets/tdg_ingress_basic_authen#tdg_ingress_basic_authen | base64encode>
  user: <path:projects/362159383816/secrets/tdg_ingress_basic_authen_user#tdg_ingress_basic_authen_user | base64encode>
  password: <path:projects/362159383816/secrets/tdg_ingress_basic_authen_password#tdg_ingress_basic_authen_password | base64encode>