apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: google_credentials-creds
data:
  google_credentials.json: <path:projects/362159383816/secrets/google_credentials_json#google_credentials_json | base64encode>